global:
  scrape_interval: 6s

scrape_configs:
  - job_name: "api_gestao_vagas"
    metrics_path: "/actuator/prometheus"
    static_configs:
    - targets: ["localhost:8080"]
      labels:
        application: "api_gestao_vagas" 
